---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-terminal
---
apiVersion: controller.devfile.io/v1alpha1
config:
  workspace:
    idleTimeout: 8h
    imagePullPolicy: Always
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  namespace: openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: web-terminal
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
  labels:
    console.openshift.io/terminal: "true"
  name: web-terminal-tooling
  namespace: openshift-operators
spec:
  attributes:
    controller.devfile.io/storage-type: per-workspace
  components:
  - container:
      args:
      - tail
      - -f
      - /dev/null
      cpuLimit: 800m
      cpuRequest: 100m
      image: quay.io/noeloc/opencode:latest
      memoryLimit: 4096Mi
      memoryRequest: 128Mi
      mountSources: false
      sourceMapping: /home/user/workspace
      volumeMounts:
      - name: work-storage
        path: /home/user/workspace
      - name: cli-storage
        path: /home/user/.local
    name: web-terminal-tooling
  - name: work-storage
    volume:
      ephemeral: false
  - name: cli-storage
    volume:
      ephemeral: false
